/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImageRouteImport } from './routes/image'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ApiPublicCachestatusRouteImport } from './routes/api/public/cachestatus'
import { Route as ApiPublicBustcacheRouteImport } from './routes/api/public/bustcache'

const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCachestatusRoute = ApiPublicCachestatusRouteImport.update({
  id: '/api/public/cachestatus',
  path: '/api/public/cachestatus',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBustcacheRoute = ApiPublicBustcacheRouteImport.update({
  id: '/api/public/bustcache',
  path: '/api/public/bustcache',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/checkout': typeof CheckoutRoute
  '/image': typeof ImageRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/bustcache': typeof ApiPublicBustcacheRoute
  '/api/public/cachestatus': typeof ApiPublicCachestatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/checkout': typeof CheckoutRoute
  '/image': typeof ImageRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/bustcache': typeof ApiPublicBustcacheRoute
  '/api/public/cachestatus': typeof ApiPublicCachestatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/checkout': typeof CheckoutRoute
  '/image': typeof ImageRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/api/public/bustcache': typeof ApiPublicBustcacheRoute
  '/api/public/cachestatus': typeof ApiPublicCachestatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/checkout'
    | '/image'
    | '/sitemap/xml'
    | '/api/public/bustcache'
    | '/api/public/cachestatus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/checkout'
    | '/image'
    | '/sitemap/xml'
    | '/api/public/bustcache'
    | '/api/public/cachestatus'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/checkout'
    | '/image'
    | '/sitemap/xml'
    | '/api/public/bustcache'
    | '/api/public/cachestatus'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  CheckoutRoute: typeof CheckoutRoute
  ImageRoute: typeof ImageRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ApiPublicBustcacheRoute: typeof ApiPublicBustcacheRoute
  ApiPublicCachestatusRoute: typeof ApiPublicCachestatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cachestatus': {
      id: '/api/public/cachestatus'
      path: '/api/public/cachestatus'
      fullPath: '/api/public/cachestatus'
      preLoaderRoute: typeof ApiPublicCachestatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bustcache': {
      id: '/api/public/bustcache'
      path: '/api/public/bustcache'
      fullPath: '/api/public/bustcache'
      preLoaderRoute: typeof ApiPublicBustcacheRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  CheckoutRoute: CheckoutRoute,
  ImageRoute: ImageRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ApiPublicBustcacheRoute: ApiPublicBustcacheRoute,
  ApiPublicCachestatusRoute: ApiPublicCachestatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
